spring.application.name=sistema-aluguel-carros
server.port=8080
server.max-http-request-header-size=64KB

spring.datasource.url=jdbc:h2:file:./sistema-aluguel-carros-db;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

server.error.include-message=always
